name: Backend CI

on:
  pull_request:
    branches:
      - prod
      - develop
      - cicd/#61
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: action checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle - config
        run: ./config-service/gradlew clean build -x test
        env:
          CONFIG_GIT_URI: ${{ secrets.CONFIG_GIT_URI }}
          CONFIG_PASSPHRASE: ${{ secrets.CONFIG_PASSPHRASE }}
          CONFIG_PRIVATE_KEY: ${{ secrets.CONFIG_PRIVATE_KEY }}
          
